### ISSUE TITLE
Predictive Host Dependency Checks - it is working?

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-collect#1228]
Centreon 22.10.x (latest updates)
monitoring different remote hosts with parent/child relation between FW/Gateway and hosts behind. Every host has the same check intervals. When FW/Gateway is down, all Hosts are unreachable, but we have many times the problem that we have notifications for the hosts behind the FW/Gateway.

Predictive Host Dependency Checks is set on YES on the Engine configuration.

Any idea?

**Comment by omercier** [comment]
Hi @joschi99,
Can you send your complete `centengine.cfg` file?
Can you also confirm that the notification mentioned in 
> notifications for the hosts behind the FW/Gateway

is for hosts and not for services belonging to hosts behind the gateway?

**Comment by joschi99** [comment]
Hi @omercier,
I will close the case, probably it was a mistake.

Thank for your quick response.
