### ISSUE TITLE
Broker stats on Remote Server seems broken for input

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-collect#147]
Hello,

I have build a Centreon Remote Server with a Poller attached to it. , so i have :
Central -> RS -> Poller

I’m checking the Broker speed with Centreon plugins, who claim there is something wrong :
`CRITICAL: Endpoint input 'central-broker-master-input' Speed Events: 0/s`

In the Perfdata field :
`'speed_events_central-broker-master-input'=0events/s;0.03:;0.01:;0; 'queued_events_central-broker-master-input'=0events;0:22000;0:25000;0; 'speed_events_central-broker-master-perfdata'=0.4events/s;0.03:;0.01:;0; 'queued_events_central-broker-master-perfdata'=2events;0:22000;0:25000;0; 'speed_events_central-broker-master-sql'=0.4events/s;0.03:;0.01:;0; 'queued_events_central-broker-master-sql'=2events;0:22000;0:25000;0; 'speed_events_centreon-broker-master-rrd'=0.4events/s;0.03:;0.01:;0; 'queued_events_centreon-broker-master-rrd'=829events;0:22000;0:25000;0; 'unacknowledged_events_centreon-broker-master-rrd'=0events;;;0; 'speed_events_forward-to-master'=0.2events/s;0.03:;0.01:;0; 'queued_events_forward-to-master'=952events;0:22000;0:25000;0; 'unacknowledged_events_forward-to-master'=0events;;;0;`

The content of the JSON :
`{"asio_version": "1.18.1", "endpoint central-broker-master-input": {"central-broker-master-input-12": {"bbdo_input_ack_limit": 1000, "bbdo_unacknowledged_events": 579, "event_processing_speed": 0.056603773584905662, "last_connection_attempt": 1644254015, "last_connection_success": 1644254015, "last_event_at": 1644569705, "queue_file_enabled": false, "queued_events": 0, "read_filters": "all", "state": "connected", "unacknowledged_events": 0, "write_filters": ""}, "central-broker-master-input-13": {"bbdo_input_ack_limit": 1000, "bbdo_unacknowledged_events": 986, "event_processing_speed": 0.15151515151515152, "last_connection_attempt": 1644254015, "last_connection_success": 1644254015, "last_event_at": 1644569725, "queue_file_enabled": false, "queued_events": 0, "read_filters": "all", "state": "connected", "unacknowledged_events": 0, "write_filters": ""}, "event_processing_speed": 0, "last_connection_attempt": -1, "last_connection_success": -1, "last_event_at": 1643878667, "memory_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.memory.central-broker-master-input", "name": "central-broker-master-input", "one_peer_retention_mode": false, "peers": "0: ", "queue_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.queue.central-broker-master-input", "queued_events": 0, "read_filters": "all", "state": "listening", "write_filters": ""}, "endpoint central-broker-master-perfdata": {"event_processing_speed": 0.6875, "failover": {}, "last_connection_attempt": 1643878667, "last_connection_success": 1643878667, "last_event_at": 1644569726, "memory_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.memory.central-broker-master-perfdata", "name": "central-broker-master-perfdata", "pending events": 0, "queue_file_enabled": false, "queue_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.queue.central-broker-master-perfdata", "queued_events": 0, "read_filters": "all", "state": "connected", "status": "reading event from multiplexing engine", "unacknowledged_events": 0, "write_filters": "all"}, "endpoint central-broker-master-sql": {"conflict_manager": {"events_handled": 3, "loop timeout": 30, "max pending events": 10000, "max perfdata events": 10000, "speed": "0.2 events/s", "sql": 0, "storage": 0, "waiting_events": 0}, "event_processing_speed": 0.6875, "failover": {}, "last_connection_attempt": 1643878667, "last_connection_success": 1643878667, "last_event_at": 1644569726, "memory_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.memory.central-broker-master-sql", "name": "central-broker-master-sql", "queue_file_enabled": false, "queue_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.queue.central-broker-master-sql", "queued_events": 0, "read_filters": "all", "sql pending events": 0, "state": "connected", "status": "reading event from multiplexing engine", "unacknowledged_events": 0, "write_filters": "all"}, "endpoint centreon-broker-master-rrd": {"bbdo_input_ack_limit": 1000, "bbdo_unacknowledged_events": 0, "event_processing_speed": 0.6875, "failover": {}, "last_connection_attempt": 1643878667, "last_connection_success": 1643878667, "last_event_at": 1644569726, "memory_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.memory.centreon-broker-master-rrd", "name": "centreon-broker-master-rrd", "queue_file_enabled": false, "queue_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.queue.centreon-broker-master-rrd", "queued_events": 543, "read_filters": "all", "state": "connected", "status": "reading event from multiplexing engine", "unacknowledged_events": 543, "write_filters": "all"}, "endpoint forward-to-master": {"bbdo_input_ack_limit": 1000, "bbdo_unacknowledged_events": 0, "event_processing_speed": 0.18181818181818182, "failover": {}, "last_connection_attempt": 1643878667, "last_connection_success": 1643878667, "last_event_at": 1644569725, "memory_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.memory.forward-to-master", "name": "forward-to-master", "queue_file_enabled": false, "queue_file_path": "/var/lib/centreon-broker//centreon-rs-lyon-01-broker.queue.forward-to-master", "queued_events": 200, "read_filters": "all", "state": "connected", "status": "reading event from multiplexing engine", "unacknowledged_events": 200, "write_filters": ",  service_group,  service,  service_dependency,  service_check,  host,  downtime,  event_handler,  flapping_status,  host_check,  host_dependency,  responsive_instance,  custom_variable,  instance_configuration,  comment,  service_status,  acknowledgement,  service_group_member,  custom_variable_status,  host_group,  host_group_member,  host_parent,  host_status,  instance,  instance_status,  log_entry,  module"}, "module/usr/share/centreon/lib/centreon-broker/10-neb.so": {"name": "/usr/share/centreon/lib/centreon-broker/10-neb.so", "size": "483456B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/15-stats.so": {"name": "/usr/share/centreon/lib/centreon-broker/15-stats.so", "size": "136920B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/20-bam.so": {"name": "/usr/share/centreon/lib/centreon-broker/20-bam.so", "size": "1003048B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/20-storage.so": {"name": "/usr/share/centreon/lib/centreon-broker/20-storage.so", "size": "683560B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/30-correlation.so": {"name": "/usr/share/centreon/lib/centreon-broker/30-correlation.so", "size": "148592B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/50-tcp.so": {"name": "/usr/share/centreon/lib/centreon-broker/50-tcp.so", "size": "435896B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/60-tls.so": {"name": "/usr/share/centreon/lib/centreon-broker/60-tls.so", "size": "90520B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/70-lua.so": {"name": "/usr/share/centreon/lib/centreon-broker/70-lua.so", "size": "450392B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/70-rrd.so": {"name": "/usr/share/centreon/lib/centreon-broker/70-rrd.so", "size": "426552B", "state": "loaded"}, "module/usr/share/centreon/lib/centreon-broker/80-sql.so": {"name": "/usr/share/centreon/lib/centreon-broker/80-sql.so", "size": "65880B", "state": "loaded"}, "mysql manager": {"delay since last check": "0", "waiting tasks in connection 0": "0"}, "now": "1644569728", "pid": 20883, "thread_pool": {"latency": "0.014ms", "size": 2}, "version": "20.10.11"}`

**It seems that the global "event_processing_speed" is not computed in the same way as the others.**

Broker Version on the RS :

- centreon-broker-storage-20.10.11-1.el7.centos.x86_64
- centreon-broker-cbd-20.10.11-1.el7.centos.x86_64
- centreon-broker-core-20.10.11-1.el7.centos.x86_64
- centreon-broker-20.10.11-1.el7.centos.x86_64
- centreon-broker-cbmod-20.10.11-1.el7.centos.x86_64

Thanks

**Comment by omercier** [comment]
Hi @BenoitPoulet, 
Actually those values are computed on-demand and unless they are obtained exactly at the same moment (which is impossible technically, with the current named pipes mechanism) they won't be strictly identical.
We are working on an improvement to avoid using named pipes in the future.
