### ISSUE TITLE
Install on debian 11

### ISSUE THREAD

**Issue by acayssials** [centreon/centreon-collect#312]
I have the following error when I ma on make step :

/usr/local/src/centreon-collect-22.04.0/bbdo/service.pb.h:35:10: fatal error: tag.pb.h: Aucun fichier ou dossier de ce type
   35 | #include "tag.pb.h"
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [bbdo/CMakeFiles/pb_service_lib.dir/build.make:89 : bbdo/CMakeFiles/pb_service_lib.dir/service.pb.cc.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:1576 : bbdo/CMakeFiles/pb_service_lib.dir/all] Erreur 2
make: *** [Makefile:149 : all] Erreur 2

I have tried to to setup on two vms, debian buster is up to date (11.3)

**Comment by bouda1** [comment]
Hi,

Could you just fetch last changes and try again please. Your issue is just a missing dependency in a `CMakeLists.txt` file. We have seen it recently, and I think it is fixed now.

If it still fails, could you specify what branch do you try to compile.
Thanks, cheers.
David.
